version: '3'
services:
    monitor:
      build: ./monitor/
      ports:
        - "5000:5000"

    app_1:
      build: ./app/
      environment:
        - APP_NAME=demo_app_1
    app_2:
      build: ./app/
      environment:
        - APP_NAME=demo_app_2
    app_3:
      build: ./app/
      environment:
        - APP_NAME=demo_app_3
    app_4:
      build: ./app/
      environment:
        - APP_NAME=demo_app_4
